export const ADD_TODO_REQUEST = 'ADD_TODO_REQUEST';
export const ADD_TODO_SUCCSESS = 'ADD_TODO_SUCCSESS';
export const ADD_TODO_FAILURE = 'ADD_TODO_FAILURE';

export const GET_TODOS_REQUEST = 'GET_TODOS_REQUEST';
export const GET_TODOS_SUCCSESS = 'GET_TODOS_SUCCSESS';
export const GET_TODOS_FAILURE = 'GET_TODOS_FAILURE';

export const PUT_CHANGE_IS_DONE_REQUEST = 'PUT_CHANGE_IS_DONE_REQUEST';
export const PUT_CHANGE_IS_DONE_SUCCSESS = 'PUT_CHANGE_IS_DONE_SUCCSESS';
export const PUT_CHANGE_IS_DONE_FAILURE = 'PUT_CHANGE_IS_DONE_FAILURE';

export const EDIT_TODO_REQUEST = 'EDIT_TODO_REQUEST';
export const EDIT_TODO_SUCCSESS = 'EDIT_TODO_SUCCSESS';
export const EDIT_TODO_FAILURE = 'EDIT_TODO_FAILURE';

export const REMOVE_TODOS_TO_TRASH_REQUEST = 'REMOVE_TODOS_TO_TRASH_REQUEST';
export const REMOVE_TODOS_TO_TRASH_SUCCSESS = 'REMOVE_TODOS_TO_TRASH_SUCCSESS';
export const REMOVE_TODOS_TO_TRASH_FAILURE = 'REMOVE_TODOS_TO_TRASH_FAILURE';

export const DELETE_PERMANENTLY_REQUES = 'DELETE_PERMANENTLY_REQUES';
export const DELETE_PERMANENTLY_SUCCSESS = 'DELETE_PERMANENTLY_SUCCSESS';
export const DELETE_PERMANENTLY_FAILURE = 'DELETE_PERMANENTLY_FAILURE';

export const SET_CURRENT_TODO_ID = 'SET_CURRENT_TODO_ID';
